#!/bin/bash
set -e

echo ""
echo "============================="
echo "| Linking libraries         |"
echo "============================="
echo ""
ldconfig

echo ""
echo "============================="
echo "| Clean up and fix perms    |"
echo "============================="
echo ""

chown -R pi:pi /home/pi
chown -R pi:pi /usr/local
chown -R pi:pi /usr/lib/python2.7/dist-packages/

echo ""
echo "============================="
echo "|      <<< Done >>>         |"
echo "============================="
echo ""
